name: blume_system
version: 1.0
main: blume_system.general.Main

commands:
   stats:
      description: none
      usage: /<command>
   ranks:
      description: none
      usage: /<command>
   rankuptest:
      description: none
      usage: /<command>
   makemepro:
      description: none
      usage: /<command>
   resetbody:
      description: none
      usage: /<command>
   ops:
      description: none
      usage: /<command>
   deops:
      description: none
      usage: /<command>
   spawn_buyer:
      description: none
      usage: /<command>
   spawn_seller:
      description: none
      usage: /<command>
   spawn_bank:
      description: none
      usage: /<command>
   spawn_level:
      description: none
      usage: /<command>
   villageroverkill:
      description: none
      usage: /<command>